FROM connexiolabs/base:latest

MAINTAINER John Allen <john.allen@connexiolabs.com>

RUN apt-get install -yq build-essential openssl libreadline6   \
  libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev  \
  libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev   \
  autoconf libc6-dev ncurses-dev automake libtool bison        \
  subversion pkg-config libmysqlclient-dev libpq-dev make wget \
  unzip git vim nano nodejs mysql-client mysql-server gawk     \
  libgdbm-dev libffi-dev
